---
- name: "Server configuration"
  hosts: server
  user: ubuntu
  gather_facts: false
  become: yes
  become_method: sudo
  become_user: root
  
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
      
    - name: "Install 'unzip'"
      apt:
        name: [ "unzip" ]
        state: latest
        update_cache: yes
        
    - name: "install python for Ansible."
      become: true
      apt:
        name: "python3"
        state: "latest"
        update_cache: yes

  roles:
    - install-dependencies

- name: "Configure AWS CLI"
  hosts: server
  user: ubuntu
  gather_facts: false
  become: yes
  become_method: sudo
  become_user: root
  vars:
    AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
  tasks:
    - name: Set access key
      shell: "aws configure set aws_access_key_id {{ AWS_ACCESS_KEY_ID }}"
    - name: Set secret key
      shell: "aws configure set aws_secret_access_key {{ AWS_SECRET_ACCESS_KEY }}"
    - name: Set default region
      shell: "aws configure set default.region {{ AWS_DEFAULT_REGION }}"

- name: "Fetch kubectl config"
  hosts: server
  user: ubuntu
  gather_facts: false
  become: yes
  become_method: sudo
  become_user: root
  vars:
    AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  pre_tasks:
    - name: Add new context to kubeconfig
      shell: "aws eks update-kubeconfig --region us-east-1 --name capstone-project-cluster"
