---
- name: "Configure EKS cluster"
  hosts: server
  user: ubuntu
  gather_facts: false
  become: yes
  become_method: sudo
  become_user: root
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  roles:
    - kubernetes-manifest
