- name: "Deploy app to kubernetes"
  hosts: server
  user: ubuntu
  gather_facts: false
  become: yes
  become_method: sudo
  become_user: root
  vars:
    CIRCLE_WORKFLOW_ID: "{{ lookup('env', 'CIRCLE_WORKFLOW_ID') }}"
  tasks:
    - name: Deploy app
      shell: "kubectl set image deployments/capstone-project-deployment capstone-project-app=manhnguyen308/capstone-project-app:{{ CIRCLE_WORKFLOW_ID }}"
      args:
        chdir: $HOME

    - name: Check deployment status
      shell: "kubectl rollout status deployments/capstone-project-deployment"
      args:
        chdir: $HOME
