---
- name: "Download kubectl"
  become: yes
  shell: curl -LO https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl
  args:
    chdir: $HOME

- name: "Apply Execute permission"
  become: yes
  shell: chmod +x ./kubectl
  args:
    chdir: $HOME

- name: "Copy kubectl to $HOME"
  become: yes
  shell: install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  args:
    chdir: $HOME

- name: "Add path to shell file"
  become: yes
  shell: echo 'export PATH=$PATH:/usr/local/bin' >> .bashrc
  args:
    chdir: $HOME