version: 2.1

jobs:
  build-code:
    docker:
      - image: python:3.7.3-stretch

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      # run build
      - run:
          name: install dependencies
          command: |
            make setup
            make install

      # run lint
      - run:
          name: run lint
          command: |
            make setup
            make lint

      - save_cache:
          paths:
            - ~/.devops
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  upload-docker:
    docker:
      - image: circleci/golang:1.15

    working_directory: ~/project

    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Build docker container
          command: |
            docker build --tag=$DOCKER_IMAGE .
            docker image ls

      - run:
          name: Upload Docker to Dockerhub
          command: |
            echo "Docker ID and Image: $DOCKER_IMAGE"
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            docker tag $DOCKER_IMAGE $DOCKER_USERNAME/$DOCKER_IMAGE:${CIRCLE_WORKFLOW_ID:0:7}
            docker push $DOCKER_USERNAME/$DOCKER_IMAGE:${CIRCLE_WORKFLOW_ID:0:7}

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure EKS network exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/server/network.yml \
              --tags project=${CIRCLE_WORKFLOW_ID:0:7}-project \
              --stack-name "${CIRCLE_WORKFLOW_ID:0:7}-eks-network" \
              --region ${AWS_DEFAULT_REGION} \
              --parameters .circleci/server/network-params.json
      - run:
          name: Ensure EKS Cluster exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/server/eks-cluster.yml \
              --tags project=${CIRCLE_WORKFLOW_ID:0:7}-project \
              --stack-name "${CIRCLE_WORKFLOW_ID:0:7}-eks-cluster" \
              --region ${AWS_DEFAULT_REGION} \
              --parameters .circleci/server/eks-cluster-params.json \
              --capabilities CAPABILITY_NAMED_IAM
          no_output_timeout: 15m
      - run:
          name: Ensure Nodegroup exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/server/amazon-eks-nodegroup.yml \
              --tags project=${CIRCLE_WORKFLOW_ID:0:7}-project \
              --stack-name "${CIRCLE_WORKFLOW_ID:0:7}-eks-nodegroup" \
              --region ${AWS_DEFAULT_REGION} \
              --parameters .circleci/server/amazon-eks-nodegroup-params.json \
              --capabilities CAPABILITY_NAMED_IAM


  deploy-docker:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "66:5e:74:b3:10:7b:88:b8:23:a3:48:fc:07:48:5c:b4"
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Deploy newest Docker Image
          command: |
            cat ~/inventory.txt
            cd ansible
            ansible-playbook -i ~/inventory.txt deploy-app.yml
          no_output_timeout: 2m

workflows:
  default:
    jobs:
      - build-code
      - upload-docker:
          requires:
            - build-code
          filters:
            branches:
              only: [ main ]
      - deploy-infrastructure:
          filters:
            branches:
              only: [ main ]