apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project-deployment
  labels:
    app: capstone-project-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-project-app
  template:
    metadata:
      labels:
        app: capstone-project-app
    spec:
      containers:
        - name: capstone-project-app
          image: docker.io/manhnguyen308/capstone-project:latest
          ports:
            - containerPort: 80
