- name: Copy deployment configuration
  copy:
    src: "kubernetes-deployment-manifest.yaml"
    dest: $HOME

- name: Apply deployment configuration
  shell: "kubectl apply -f kubernetes-deployment-manifest.yaml"
  args:
    chdir: $HOME

- name: Copy service configuration
  copy:
    src: "kubernetes-service-manifest.yaml"
    dest: $HOME

- name: Create service configuration
  command: "kubectl apply -f kubernetes-service-manifest.yaml"
  args:
    chdir: $HOME